spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:minseo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

hodolman:
  jwt-key: "fgIBqD11TOyi9YSHqZ8Pzt7EndLGo5W10PC6GgiB5vs="